src/app.js
If you have over 999 unread email you get a , in your unread count. ie 1,001
Updated regex to match.
Not sure if you get more commas the more unread you have.
=> Fix for , in Window title

package.json, src/app.js, src/menu.js
Add mailto support to the app.
I've added a new menu to the app called settings. Ideally it would only need one button and track if MailTo support has been enabled already yet.
Would you want that change for the button or are you happy as is?
Edit: Made the above menu change.
=> add mailto support

src/app.js
Often ueed by thirdparty IDPs / SAML auth services.
=> Fixes #2. Disabled nodeIntegration to fix jQuery

src/app.js
Fixes #10 
```
(\d+[,]?\d+)
```
This pattern will fail for any inbox count with single digits, because it will be looking for two different instances of (1 or more) digits.  There are a few potential fixes for this, but I don't know which is the most correct.  I went with the simple case of making the second pattern be (0 or more) digits.  Some alternatives
```
([\d,]+)
```
This would match any combination of numbers and commas.
```
(\d+(?:,\d+)*)
```
I think that would match any list of comma-separated numbers.
=> Fixed regular expression for single-digit unread counts

src/app.js, src/preload.js
Currently, the unread count changes based on which label you are in and if you have an email open, the unread count will never change since the title doesn't reflect the unread count.  This aims to solve this problem using the following process.
1. Add a preload script to the main window so we can execute JS code in Gmail.
1. When changes occur, grab the unread count from the inbox label on the left navigation bar
Changes to the unread count are tracked using one of two ways.
1. A MutationObserver that observes the title.  Even though the title does not always work for getting the unread count, it is a good event to listen to for checking the unread count.
1. An interval of 1 second (configurable through the `INTERVAL` const in preload.js) will check the unread count every second.  I …
=> Fix unread count

src/menu.js, src/state/window.js
Fixes #31 
I added a Develop menu that currently only contains one item labeled "Clear cache and restart".  Clicking that item will clear the app state and restart the application without triggering any before-quit type events.  This allows us to quite the application without saving the current size to simulate how the app works if it was the first time starting it.
=> Default window size

src/app.js, src/debug.js, src/menu.js
This is not a finished PR as I still would like to explore reloading the menu when the settings change as well as enabling or disabling `electronDebug`.
Fixes #33
=> Only enable debug features when developer mode is enabled

src/state/window.ts
I accidentally reversed the conditional when we updated to TypeScript.  Fixes #52
=> Fix window state not saving

package.json
I think this should fix the update problems we are having in #47.  I haven't tested the output for Windows, but Mac and Linux appear to build the proper file names.  @timche Could you test this for Windows?
=> Specify artifact name to fix auto updater issues

package.json
Same issue on Windows as explained here: https://github.com/sindresorhus/caprine/issues/752#issuecomment-458648468
=> disable windows code signature check on update

src/app.ts
`showCopyImageAddress` and `showSaveImageAs` are disabled by default.
=> fix context menu missing image actions

src/app.ts, src/helpers.ts
Currently when adding a new or switching to another account their links will be opened in a new window instead in the main window.
=> fix account switching

css/style.css
Gmail shipped an update which changed the search bar and its classes.
Before:
After:
=> fix search bar styles

src/app.ts
The fullscreen option of browser window doesn't actually set fullscreen but enables/disables it from being used.
=> Fix fullscreen

css/style.css, css/style.macos.css
Fixes a number of issues with the recent custom style changes.
- Adds selectors for dragging headers for new windows and pdf viewer
- Adds left padding for macos for new window and pdf viewer headers
- Fix height for G Suite account links (it is larger than the normal account avatar)
=> More custom style fixes

src/app.ts, src/downloads.ts
Since adding electron-dl it has been frustrating because there is no visual indicator that downloads are processing except for the progress bar in the dock.  This adds notifications when downloads are complete.  I added an action of "Open" to the download notification so users could open the item.
=> Add download notifications

css/style.css, css/style.macos.css, src/custom-styles.ts, src/preload.ts
This adds a listener to the Electron full screen events to add a body class that will align the hamburger menu on OSX.
Fixes #87
=> Align hamburger menu when app is in full screen on OSX

src/app.ts, src/config.ts, src/menu.ts
1. Uses the new `--start-minimized`  [command line switch](https://electronjs.org/docs/api/app#appcommandlinehasswitchswitch) to decide if the app should start minimized.
2. Bug fix: The tray context menu item "Show" wasn't being updated. Meaning, when the app is open, tray should say "Hide" and vice-versa. This has now been fixed.
Verified these changes on Linux and Windows, someone else has to dirty test it on macOS.
Thoughts?
=> Support starting app minimized to tray

src/app.ts, src/config.ts, src/menu.ts, src/utils.ts
This fixes #88 by adding a configurable option to set the visibility of the Menu bar for those who want to change it.
When the Menu bar is hidden, we can hit the Alt key once to bring it up.
With Menu bar visible (current look):
With Menu bar hidden (new look):
Thoughts?
=> fix issue #88 by adding option to hide Menu bar

src/preload.ts
The regex for the unread count was only catching single number values.
=> Unread count for greater than 9 emails

src/app.ts
Bug description:
On WIndows, and Linux, the Tray context menu displays a "Hide/Show" item, but due to a coding error, that item wasn't created on Windows and thus lead to a null reference error at runtime for Windows users. This PR fixes that by creating the said Tray item on both Windows and Linux and thus closes #167 .
=> fix #167 by creating tray items on woedows too

package.json, src/app.ts, src/menu.ts, src/utils.ts, yarn.lock
With Electron 6, the macOS menu bar icon displays as semi-transparent/grayish under the dark theme. This is an upstream issue with Electron and has been fixed under Electron 7. This PR upgrades the Electron dependency to version 7 and makes all necessary changes to make it build and run. Preliminary testing shows that the upgrade should be fine, but further testing may be needed.
=> Upgrade to Electron 7 to Solve Menu Bar Icon Issue

src/main/menus/app.ts
Leaves empty space on top once disabled, and after restarting the app, once activated with Alt, fails to render, can only see the outline around the items. Once one of the items is selected, though, the submenu renders correctly. But this is a separate issue.
=> Fix 'hide menu bar' menu item

src/main/main-window/index.ts
When running gmail-desktop on Linux/X11 a generic fallback icon is shown in the titlebar.  The path for the included icon appears to be slightly off.  This PR changes the path to fix that problem.
Before:
After:
=> Fix missing application icon on Linux

src/main/account-views/custom-styles/style.css
I simply took the padding and margin values from here:
And it just worked...
Before:
After:
Tested on Mac and Windows.
=> fix settings button alignment in compact header

src/main/account-views/custom-styles/style.css
=> fix google chat status in compact header mode

src/main/app.ts, src/main/menus/app.ts
On Mac, you can press Cmd+W to close the window, and still access the menu bar. Some options which I expected to reopen the main window didn't do so, but others did.
Now, the main window will open/focus when you press any of: Gmail Settings, Add Account, Edit Account, Remove Account.
It will also open/focus when handling a mailto link.
=> open main window on some actions (macOS)

src/main/account-views/preload/dark-mode.ts
The code is a bit janky, but the screenshots are pretty.
Before:
After:
Light mode for reference:
=> improve the look of the sign-in page in dark mode

src/main/menus/app.ts
I don't think the "Hide", "Hide Others" and "Show All" buttons do anything on Windows or Linux.
I removed the "Hide" and "Hide Others" accelerators because they are provided by default on macOS. "Hide Others" now gets set to `Command+Option+H` instead of `Command+Shift+H`. (Safari and Chrome use `Command+Shift+H` to go Home, so we could potentially use that hotkey to go to the inbox or something.)
The `visible` property doesn't hide separators (electron/electron#3494), so I've used a quick and dirty solution.
=> use hide window buttons on macos only

README.md
Made it clear that you need to enable desktop notifications in Gmail for notifications to work. Otherwise I would just assume that notifications are on by default (like in the official Android app).
=> Make it clear that you need to enable desktop notifications in Gmail

src/main/downloads.ts
Fix for #364 
using getSavePath to retrieve the downloaded files full path
=> downloads: use actual save path when opening

src/main/accounts.ts, src/main/menus/app.ts
This PR adds menu bar items and keyboard shortcuts for native style tab navigation between accounts.
Note that both shortcuts are able to "cycle" back around, i.e. if you invoke "next" on the rightmost tab then the leftmost tab will be selected and vice-versa.
=> Add menu items for next/previous account selection
