src/menu.js

Update location of report issue link

---

package.json
src/app.ts
yarn.lock

To understand what's happening with the update mechanism, add logging to auto-updater. This is to debug #47.

add logging to auto-updater

---

css/style.css
src/app.ts
src/menu.ts
src/minimal-mode.ts
src/preload.ts
src/utils.ts

Adds a new minimal mode to clean up some of the messy Gmail interface.  Fixes #59

Minimal mode

---

css/style.css
css/style.macos.css
package.json
src/app.ts
yarn.lock

Fix new window header

---

src/app.ts

Open links from new windows in an external browser

---

package.json
src/app.ts
src/preload.ts
yarn.lock

Close new window when email is archived, marked as spam, or deleted

---

package.json
src/app.ts

I've registered https://timche.dev for my personal website and want to use this as app id.

change app id

---

package.json
src/app.ts
yarn.lock

enhance download experience + add context menu

---

src/app.ts

Something that we have overlooked and isn't picked up by TS somehow.

fix last window state maximized

---

css/style.css

Missed a couple of class updates that prevent title bar dragging.

Fix title bar drag styles

---

css/style.css
src/app.ts
src/config.ts
src/debug.ts
src/menu.ts
src/utils.ts

Start on css fixes

---

css/style.css
css/style.macos.css

Hey Tim, long time no speak!  I hope all is well.
I switched back to using gmail desktop a month or two ago and I wanted to contribute some more to the project.  The first thing that was bugging me was the custom styles not working.  As I mentioned in https://github.com/timche/gmail-desktop/issues/121, I reworked the custom styles to be based on element position rather than class names.  We can see how it works but I am hoping it will be much more stable than the class name approach.  Additionally, I commented on every line of the stylesheet as there were styles in the old stylesheet that I had no idea why they were there because the class names have since changed.  By keeping every style commented, we can always fix the selectors because we know the intent of the style.

Update custom styles

---

src/app.ts
src/auto-updates.ts

Add update notifications

---

README.md
src/app.ts
src/custom-styles.ts
src/menu.ts

Adds the ability for users to define custom styles using a custom css file.
Closes #77

Custom styles

---

package.json

Add .rpm package to existing linux build targets (fixes #91)

---

src/app.ts

Also clean google tracking from push notification emails

---

package.json
src/app.ts
src/config.ts
yarn.lock

Show the real destination URL to avoid phishing attempt.
#187

confirm destination URL before open link

---

README.md

I have been using your app for awhile now and just created a cask for it. Just thought I add the installation via homebrew.

Add installation via homebrew cask

---

src/downloads.ts

Don't notify the user if showing the file location

---

src/main/accounts.ts
src/main/app.ts
src/main/gmail.ts
src/main/main-window/index.ts
src/main/menus/app.ts
src/main/menus/dock.ts
src/main/menus/tray.ts
src/main/tray.ts
src/main/updater.ts

fix show main window when maximized and minimized on windows

---

src/main/main-window/index.ts

fix mouse back/forward triggering twice

---

src/main/account-views/preload/dark-mode.ts

Settings > General > Language > Enable input tools
Please try this out and let me know what you think 🙂

fix input tools in dark mode

---

src/main/utils/url.ts

links: add copy to clipboard option

---

src/main/account-views/preload/gmail.ts

I just realized that the fix I did was on the main branch :sweat:, here's the same fix, tested on alpha build.
Closes #328

fix: Unread message indicator in status bar (develop)
